### ISSUE TITLE
Cannot make Network Traffic Object. (help required with src_ref and dst_ref)

### ISSUE THREAD

**Issue by mmali277** [oasis-tcs/cti-stix2#92]
Please can some one help me, I am new to stix2, i just want to make Network Traffic Object.
Code:

from stix2 import Indicator,NetworkTraffic,ObservedData,SocketExt,AutonomousSystem,ObservableProperty
network=NetworkTraffic(protocols=["ipv4-addr"],src_ref="0")
print(network)

Output:
Traceback (most recent call last):
  File "C:/Users/DELL/PycharmProjects/Cowrie_to_Stix2/cowrie_to_stix2.py", line 2, in <module>
    network=NetworkTraffic(protocols=["ipv4-addr"],src_ref="0")
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\stix2\base.py", line 274, in __init__
    super(_Observable, self).__init__(**kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\stix2\base.py", line 160, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\stix2\base.py", line 304, in _check_property
    self._check_ref(ref, prop, prop_name)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\site-packages\stix2\base.py", line 281, in _check_ref
    raise InvalidObjRefError(self.__class__, prop_name, "'%s' is not a valid object in local scope" % ref)
stix2.exceptions.InvalidObjRefError: Invalid object reference for 'NetworkTraffic:src_ref': '0' is not a valid object in local scope

I know i am doing it wrong, but i have try many option like object reference property etc. I just want to make the following output:

{
"0": {
"type": "ipv4-addr",
"value": "198.51.100.2"
},
"1":{
"type": "ipv4-addr",
"value": "198.51.100.3"
},
"2": {
"type": "network-traffic",
"src_ref": "0",
"dst_ref": "1",
"protocols": [
"tcp"
]
}
}

I have checked this one
 
asa = AutonomousSystem(type="autonomous-system",number=15139,name="Slime 
print(asa.serialize())

and it gives fine result:

{
    "type": "autonomous-system",
    "number": 15139,
    "name": "Slime Industries",
    "rir": "ARIN"
}

**Comment by mmali277** [comment]
solved my issue.

**Comment by ssachd4** [comment]
@mmali277 Can you let me know how you solved this issue? I am running into the same error.
